import { _ } from '../helper.js'

export default {
  title: _('面板术语表', 'ClawPanel Glossary', '面板術語表', '用語集', '용어집', 'Bảng thuật ngữ', 'Glosario', 'Glossário', 'Глоссарий', 'Glossaire', 'Glossar'),
  desc: _('面板里出现的技术词，用大白话解释一遍。点击右上角「打开页面」直达对应配置。', 'Plain-language explanations of every tech term in the panel. Click "Open page" to jump to the matching settings.', '面板裡出現的技術詞，用大白話解釋一遍。點擊右上角「打開頁面」直達對應設定。', 'パネル内の専門用語をやさしい言葉で解説。「ページを開く」をクリックで対応設定へ', '패널의 기술 용어를 쉬운 말로 설명. "페이지 열기"를 클릭하면 해당 설정으로 이동', 'Giải thích các thuật ngữ kỹ thuật trong panel bằng ngôn ngữ đơn giản. Bấm "Mở trang" để tới phần cấu hình tương ứng', 'Términos técnicos del panel explicados con palabras sencillas. Pulsa "Abrir página" para ir a la configuración correspondiente', 'Termos técnicos do painel explicados em linguagem simples. Clique em "Abrir página" para ir à configuração correspondente', 'Технические термины панели простыми словами. Нажмите «Открыть страницу», чтобы перейти к настройкам', 'Termes techniques du panneau expliqués simplement. Cliquez sur « Ouvrir la page » pour accéder aux réglages', 'Technische Begriffe des Panels in einfachen Worten erklärt. Klicken Sie auf „Seite öffnen" um zur Einstellung zu gelangen'),
  searchPlaceholder: _('搜索术语，比如 Gateway、Agent、Token...', 'Search terms like Gateway, Agent, Token...', '搜尋術語，例如 Gateway、Agent、Token...', '用語を検索: Gateway、Agent、Token...', '용어 검색: Gateway, Agent, Token...', 'Tìm thuật ngữ: Gateway, Agent, Token...', 'Buscar términos: Gateway, Agent, Token...', 'Buscar termos: Gateway, Agent, Token...', 'Поиск терминов: Gateway, Agent, Token...', 'Rechercher: Gateway, Agent, Token...', 'Begriffe suchen: Gateway, Agent, Token...'),
  noMatch: _('没有匹配的术语', 'No matching terms', '沒有符合的術語', '一致する用語なし', '일치하는 용어 없음', 'Không có thuật ngữ phù hợp', 'Sin coincidencias', 'Sem correspondências', 'Совпадений не найдено', 'Aucune correspondance', 'Keine Übereinstimmung'),
  openPage: _('打开页面', 'Open page', '打開頁面', 'ページを開く', '페이지 열기', 'Mở trang', 'Abrir página', 'Abrir página', 'Открыть страницу', 'Ouvrir la page', 'Seite öffnen'),
}
