import { _ } from '../helper.js'

export default {
  floorBlocker: {
    title: _("内核版本过低", "Kernel version too old", "核心版本過低", "カーネルバージョンが古すぎます", "커널 버전이 너무 낮습니다", "Phiên bản kernel quá cũ", "Versión del kernel demasiado antigua", "Versão do kernel muito antiga", "Версия ядра слишком старая", "Version du noyau trop ancienne", "Kernel-Version zu alt"),
    message: _("当前 OpenClaw 内核版本 {current} 低于 ClawPanel 支持的最低版本 {floor}，部分功能可能无法工作。", "OpenClaw kernel {current} is below the minimum supported version {floor}. Some features may not work.", "目前 OpenClaw 核心版本 {current} 低於 ClawPanel 支援的最低版本 {floor}，部分功能可能無法運作。", "OpenClaw カーネル {current} は ClawPanel がサポートする最低バージョン {floor} を下回っています。一部機能が動作しない可能性があります。", "현재 OpenClaw 커널 {current} 은 ClawPanel 의 최소 지원 버전 {floor} 보다 낮습니다. 일부 기능이 작동하지 않을 수 있습니다.", "Kernel OpenClaw {current} thấp hơn phiên bản tối thiểu được hỗ trợ {floor}. Một số tính năng có thể không hoạt động.", "El kernel de OpenClaw {current} está por debajo de la versión mínima soportada {floor}. Algunas funciones podrían no funcionar.", "O kernel OpenClaw {current} está abaixo da versão mínima suportada {floor}. Alguns recursos podem não funcionar.", "Версия ядра OpenClaw {current} ниже минимально поддерживаемой {floor}. Некоторые функции могут не работать.", "Le noyau OpenClaw {current} est inférieur à la version minimale prise en charge {floor}. Certaines fonctionnalités peuvent ne pas fonctionner.", "OpenClaw-Kernel {current} liegt unter der minimal unterstützten Version {floor}. Einige Funktionen funktionieren möglicherweise nicht."),
    targetHint: _("推荐升级到 {target} 以获得最佳体验。", "Upgrading to {target} is recommended for the best experience.", "建議升級到 {target} 以獲得最佳體驗。", "最高の体験のため {target} へのアップグレードを推奨します。", "최상의 경험을 위해 {target} 으로 업그레이드를 권장합니다.", "Khuyến nghị nâng cấp lên {target} để có trải nghiệm tốt nhất.", "Se recomienda actualizar a {target} para una mejor experiencia.", "Recomenda-se atualizar para {target} para a melhor experiência.", "Рекомендуется обновиться до {target} для лучшего опыта.", "Il est recommandé de passer à {target} pour la meilleure expérience.", "Ein Upgrade auf {target} wird für die beste Erfahrung empfohlen."),
    goUpgrade: _("前往升级", "Upgrade now", "前往升級", "アップグレードへ", "업그레이드", "Nâng cấp ngay", "Actualizar ahora", "Atualizar agora", "Обновить", "Mettre à niveau", "Jetzt upgraden"),
    continueReadonly: _("继续使用（只读模式）", "Continue (read-only)", "繼續使用（唯讀模式）", "続行（読み取り専用）", "계속 (읽기 전용)", "Tiếp tục (chỉ đọc)", "Continuar (solo lectura)", "Continuar (somente leitura)", "Продолжить (только чтение)", "Continuer (lecture seule)", "Fortfahren (schreibgeschützt)"),
    readonlyHint: _("只读模式下，写入操作会被前端校验拦截，避免破坏老内核的配置。", "In read-only mode, write operations are blocked client-side to avoid corrupting older kernel configs.", "唯讀模式下，寫入操作會被前端攔截，避免破壞舊核心的設定。", "読み取り専用モードでは、古いカーネル設定を壊さないよう書き込み操作はクライアント側でブロックされます。", "읽기 전용 모드에서는 구 커널 설정을 손상시키지 않도록 쓰기 작업이 클라이언트 측에서 차단됩니다.", "Ở chế độ chỉ đọc, các thao tác ghi sẽ bị chặn ở phía client để tránh làm hỏng cấu hình kernel cũ.", "En modo solo lectura, las operaciones de escritura se bloquean en el cliente para evitar dañar configuraciones de kernels antiguos.", "No modo somente leitura, operações de escrita são bloqueadas no cliente para evitar corromper configurações de kernels antigos.", "В режиме только чтения операции записи блокируются на стороне клиента, чтобы не повредить конфиги старых ядер.", "En mode lecture seule, les opérations d'écriture sont bloquées côté client pour éviter de corrompre les configurations d'anciens noyaux.", "Im schreibgeschützten Modus werden Schreibvorgänge clientseitig blockiert, um alte Kernel-Konfigurationen nicht zu beschädigen."),
  },
  badge: {
    currentKernel: _("当前内核", "Kernel", "目前核心", "カーネル", "커널", "Kernel", "Kernel", "Kernel", "Ядро", "Noyau", "Kernel"),
    featuresEnabled: _("已启用 {enabled}/{total} 个特性", "{enabled}/{total} features enabled", "已啟用 {enabled}/{total} 個特性", "{enabled}/{total} 機能が有効", "{enabled}/{total} 기능 활성화", "{enabled}/{total} tính năng đã bật", "{enabled}/{total} funciones habilitadas", "{enabled}/{total} recursos habilitados", "{enabled}/{total} функций включено", "{enabled}/{total} fonctionnalités activées", "{enabled}/{total} Funktionen aktiviert"),
    belowTarget: _("低于推荐版", "Below recommended", "低於推薦版", "推奨より低い", "권장 이하", "Dưới khuyến nghị", "Bajo la recomendada", "Abaixo do recomendado", "Ниже рекомендуемого", "Sous la version recommandée", "Unter der empfohlenen"),
    latest: _("已是最新", "Latest", "已是最新", "最新", "최신", "Mới nhất", "Más reciente", "Mais recente", "Последняя", "À jour", "Aktuell"),
    unknown: _("未知", "Unknown", "未知", "不明", "알 수 없음", "Không xác định", "Desconocido", "Desconhecido", "Неизвестно", "Inconnu", "Unbekannt"),
  },
  upgrade: {
    title: _("升级 OpenClaw 内核", "Upgrade OpenClaw kernel", "升級 OpenClaw 核心", "OpenClaw カーネルをアップグレード", "OpenClaw 커널 업그레이드", "Nâng cấp kernel OpenClaw", "Actualizar kernel de OpenClaw", "Atualizar kernel do OpenClaw", "Обновить ядро OpenClaw", "Mettre à jour le noyau OpenClaw", "OpenClaw-Kernel aktualisieren"),
    confirmMessage: _("即将从 {from} 升级到 {to}。\n升级约需 2 分钟，期间 Gateway 会自动重启。继续？", "Upgrading from {from} to {to}.\nThis takes about 2 minutes; Gateway will restart automatically. Continue?", "即將從 {from} 升級到 {to}。\n升級約需 2 分鐘，期間 Gateway 會自動重啟。繼續？", "{from} から {to} へアップグレードします。\n約 2 分かかり、その間 Gateway が再起動します。続行しますか？", "{from} 에서 {to} 로 업그레이드합니다.\n약 2 분 소요되며 그동안 Gateway 가 재시작됩니다. 계속할까요?", "Sẽ nâng cấp từ {from} lên {to}.\nMất khoảng 2 phút, Gateway sẽ khởi động lại tự động. Tiếp tục?", "Se actualizará de {from} a {to}.\nTarda unos 2 minutos; Gateway se reiniciará automáticamente. ¿Continuar?", "Atualizando de {from} para {to}.\nLeva cerca de 2 minutos; Gateway será reiniciado automaticamente. Continuar?", "Обновление с {from} до {to}.\nЗаймёт около 2 минут; Gateway перезапустится автоматически. Продолжить?", "Mise à jour de {from} vers {to}.\nCela prend environ 2 minutes ; Gateway redémarrera automatiquement. Continuer ?", "Aktualisierung von {from} auf {to}.\nDauert ca. 2 Minuten, Gateway wird automatisch neu gestartet. Fortfahren?"),
    starting: _("开始升级到 {version}...", "Upgrading to {version}...", "開始升級到 {version}...", "{version} にアップグレード中...", "{version} 으로 업그레이드 중...", "Đang nâng cấp lên {version}...", "Actualizando a {version}...", "Atualizando para {version}...", "Обновление до {version}...", "Mise à jour vers {version}...", "Aktualisierung auf {version}..."),
    successMessage: _("内核升级完成", "Kernel upgrade complete", "核心升級完成", "カーネルのアップグレードが完了しました", "커널 업그레이드 완료", "Nâng cấp kernel hoàn tất", "Actualización del kernel completada", "Atualização do kernel concluída", "Обновление ядра завершено", "Mise à jour du noyau terminée", "Kernel-Update abgeschlossen"),
    successToast: _("内核升级成功", "Kernel upgraded successfully", "核心升級成功", "カーネルのアップグレードに成功しました", "커널 업그레이드 성공", "Nâng cấp kernel thành công", "Kernel actualizado correctamente", "Kernel atualizado com sucesso", "Ядро успешно обновлено", "Noyau mis à jour avec succès", "Kernel erfolgreich aktualisiert"),
    failurePrefix: _("内核升级失败:", "Kernel upgrade failed:", "核心升級失敗:", "カーネルのアップグレードに失敗:", "커널 업그레이드 실패:", "Nâng cấp kernel thất bại:", "Falló la actualización del kernel:", "Falha na atualização do kernel:", "Ошибка обновления ядра:", "Échec de la mise à jour du noyau :", "Kernel-Update fehlgeschlagen:"),
  },
  upgradeHint: {
    title: _("运行中 Gateway 可升级", "Running Gateway can be upgraded", "執行中的 Gateway 可升級", "実行中の Gateway をアップグレードできます", "실행 중인 Gateway 업그레이드 가능", "Running Gateway can be upgraded", "Running Gateway can be upgraded", "Running Gateway can be upgraded", "Running Gateway can be upgraded", "Running Gateway can be upgraded", "Running Gateway can be upgraded"),
    subtitle: _("Gateway {from} → 推荐 {to}", "Gateway {from} → recommended {to}", "Gateway {from} → 推薦 {to}", "Gateway {from} → 推奨 {to}", "Gateway {from} → 권장 {to}", "Gateway {from} → recommended {to}", "Gateway {from} → recommended {to}", "Gateway {from} → recommended {to}", "Gateway {from} → recommended {to}", "Gateway {from} → recommended {to}", "Gateway {from} → recommended {to}"),
    dismissTooltip: _("本次会话不再提醒", "Don't remind me this session", "本次工作階段不再提醒", "このセッションでは再表示しない", "이 세션에서는 알리지 않음", "Không nhắc trong phiên này", "No avisar en esta sesión", "Não avisar nesta sessão", "Не напоминать в этой сессии", "Ne plus avertir pendant cette session", "In dieser Sitzung nicht erneut anzeigen"),
  },
  tooOldForProtocol: _("Gateway 内核版本过旧，不兼容当前 ClawPanel 使用的握手协议。请把 OpenClaw 内核升级到推荐版本（{recommended}）后重试。可在「服务管理 → OpenClaw → 一键升级」中完成升级。", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway 核心版本過舊，不相容目前 ClawPanel 使用的握手協議。請將 OpenClaw 核心升級到推薦版本（{recommended}）後重試。可在「服務管理 → OpenClaw → 一鍵升級」中完成升級。", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\".", "Gateway kernel is too old and does not support the handshake protocol used by this ClawPanel. Please upgrade the OpenClaw kernel to the recommended version ({recommended}) and retry. You can upgrade from \"Services → OpenClaw → Upgrade\"."),
  deviceAuthFailed: _("Gateway 设备签名验证失败（{detail}）。ClawPanel 已尝试自动修复；请重启 Gateway 后重试，若仍失败请在服务管理中查看启动诊断。", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway 裝置簽章驗證失敗（{detail}）。ClawPanel 已嘗試自動修復；請重新啟動 Gateway 後重試，若仍失敗請在服務管理中查看啟動診斷。", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services.", "Gateway device signature verification failed ({detail}). ClawPanel attempted an automatic repair. Restart the Gateway and retry; if it persists, check startup diagnostics in Services."),
}
